spring.application.name=aj

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/aj
spring.datasource.username=aj
spring.datasource.password=aj

# Disable Spring Boot Docker Compose integration (using Podman directly)
spring.docker.compose.enabled=false
